#!/usr/bin/env bash
# =============================================================================
# build-fixture.sh — Rebuild the deterministic GSD2 gsd.db fixture
# =============================================================================
#
# Regenerates .gsd/gsd.db from .gsd/seed.sql. Safe to re-run: removes any
# existing db first. The resulting binary is committed to the repo for fast
# CI startup; this script exists so the fixture can be regenerated by any
# contributor without reverse-engineering the binary.
#
# Compatibility: Bash 3.2+ / POSIX sh; no associative arrays.
# =============================================================================
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
DB="$DIR/.gsd/gsd.db"
SEED="$DIR/.gsd/seed.sql"

if [ ! -f "$SEED" ]; then
    echo "ERROR: seed.sql not found at $SEED" >&2
    exit 1
fi

if ! command -v sqlite3 >/dev/null 2>&1; then
    echo "ERROR: sqlite3 not found on PATH" >&2
    exit 1
fi

rm -f "$DB"
sqlite3 "$DB" < "$SEED"
echo "Built $DB"
