#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# sqlite-reader.sh — SQLite Query Helpers for GSD2 Adapter
# =============================================================================
#
# Version: 1.0
# Compatibility: Bash 3.2+ (no assoc arrays, no pipe-ampersand, no typed decl)
#
# Reads from a GSD2 gsd.db SQLite database and writes intermediate TSV files
# using the adapter-interface.sh contract (write_header, append_record, etc.).
#
# Prerequisites:
#   source adapter-interface.sh   (must be sourced before this file)
#
# Uses ASCII unit separator (0x1F) as sqlite3 field delimiter to avoid
# conflicts with tabs, commas, or pipes that may appear in data.
# Replaces embedded newlines in SQL with STX (0x02) placeholder so that
# line-by-line reading works, then restores them before append_record.
# =============================================================================

# Field separator: ASCII Unit Separator (0x1F)
_SQLITE_SEP="$(printf '\x1f')"
# Placeholder for embedded newlines (STX = 0x02, never appears in real data)
_NL_PLACEHOLDER="$(printf '\x02')"

# -----------------------------------------------------------------------------
# check_sqlite3 — Verify sqlite3 CLI is on PATH
# -----------------------------------------------------------------------------
check_sqlite3() {
    if ! command -v sqlite3 >/dev/null 2>&1; then
        echo "ERROR: sqlite3 not found on PATH" >&2
        return 1
    fi
    return 0
}

# -----------------------------------------------------------------------------
# is_valid_sqlite <db_path> — Validate a SQLite database file
# -----------------------------------------------------------------------------
is_valid_sqlite() {
    local db_path="$1"

    if [ ! -f "$db_path" ]; then
        echo "ERROR: File not found: $db_path" >&2
        return 1
    fi

    # Check SQLite magic bytes (first 16 bytes: "SQLite format 3\000")
    local magic
    magic="$(head -c 15 "$db_path" 2>/dev/null)" || true
    if [ "$magic" != "SQLite format 3" ]; then
        echo "ERROR: Not a SQLite database (bad magic bytes): $db_path" >&2
        return 1
    fi

    # Verify we can run a basic query
    if ! sqlite3 "$db_path" "SELECT 1;" >/dev/null 2>&1; then
        echo "ERROR: Cannot query database: $db_path" >&2
        return 1
    fi

    return 0
}

# -----------------------------------------------------------------------------
# _sqlite_query <db_path> <sql> — Run a query with unit-separator output
#   Outputs rows with fields delimited by 0x1F, one row per line.
#   Internal helper.
# -----------------------------------------------------------------------------
_sqlite_query() {
    local db_path="$1"
    local sql="$2"
    sqlite3 -separator "$_SQLITE_SEP" "$db_path" "$sql"
}

# -----------------------------------------------------------------------------
# _nl_safe_col <col_expr> — Wrap a SQL column expression to replace embedded
#   newlines (char(10)) with STX placeholder (char(2)) so that output is
#   safe for line-by-line reading in bash.
# -----------------------------------------------------------------------------
_nl_safe_col() {
    printf "REPLACE(COALESCE(%s, ''), char(10), char(2))" "$1"
}

# -----------------------------------------------------------------------------
# _escape_stx_field <value>
#   Like escape_field from adapter-interface.sh, but also converts STX
#   placeholders (0x02) to escaped \n sequences. Called instead of
#   escape_field when data has been pre-processed with _nl_safe_col.
# -----------------------------------------------------------------------------
_escape_stx_field() {
    local val="$1"
    # Escape backslashes first to avoid double-escaping
    val="$(printf '%s' "$val" | sed 's/\\/\\\\/g')"
    # Escape tabs
    val="$(printf '%s' "$val" | sed $'s/\t/\\\\t/g')"
    # Convert STX placeholders (0x02) to escaped \n (two-char literal).
    # We use sed with the actual STX byte (generated by printf) rather
    # than tr, because macOS tr does not support \x hex escapes and
    # misinterprets \x02 as the char set {\,x,0,2}.
    local stx
    stx="$(printf '\002')"
    val="$(printf '%s' "$val" | sed "s/${stx}/\\\\n/g")"
    printf '%s' "$val"
}

# -----------------------------------------------------------------------------
# _split_and_append <file> <line> <field_count>
#   Split a unit-separator-delimited line into fields, restore STX
#   placeholders to newlines during escaping, and write a TSV record.
#   Bash 3.2 compatible (no readarray, no eval with untrusted data).
# -----------------------------------------------------------------------------
_split_and_append() {
    local file="$1"
    local line="$2"
    local field_count="$3"

    # Build a TSV line directly by splitting on unit separator and escaping
    # each field. This avoids eval and intermediate variables for arbitrary
    # field counts.
    local remainder="$line"
    local tsv_line=""
    local idx=0

    while [ "$idx" -lt "$field_count" ]; do
        local raw_field
        if [ "$idx" -lt "$((field_count - 1))" ]; then
            raw_field="${remainder%%"${_SQLITE_SEP}"*}"
            remainder="${remainder#*"${_SQLITE_SEP}"}"
        else
            raw_field="$remainder"
        fi

        local escaped
        escaped="$(_escape_stx_field "$raw_field")"

        if [ "$idx" -eq 0 ]; then
            tsv_line="$escaped"
        else
            tsv_line="${tsv_line}	${escaped}"
        fi
        idx=$((idx + 1))
    done

    printf '%s\n' "$tsv_line" >> "$file"
}

# -----------------------------------------------------------------------------
# sqlite_read_knowledge <db_path> <output_dir>
#   Read memories table -> knowledge.dat
#   Mapping: id, category, title(=first 80 chars of content), content,
#            source_file(=source_unit_id), priority(=confidence)
# -----------------------------------------------------------------------------
sqlite_read_knowledge() {
    local db_path="$1"
    local output_dir="$2"
    local outfile="${output_dir}/knowledge.dat"

    write_header "$outfile" "$KNOWLEDGE_FIELDS"

    local sql="SELECT
        COALESCE(id, ''),
        COALESCE(category, ''),
        $(_nl_safe_col "SUBSTR(content, 1, 80)"),
        $(_nl_safe_col "content"),
        COALESCE(source_unit_id, ''),
        COALESCE(CAST(confidence AS TEXT), ''),
        COALESCE(CAST(hit_count AS TEXT), '0'),
        COALESCE(created_at, ''),
        COALESCE(updated_at, ''),
        COALESCE(superseded_by, '')
    FROM memories
    ORDER BY seq;"

    _sqlite_query "$db_path" "$sql" | while IFS= read -r line; do
        [ -z "$line" ] && continue
        _split_and_append "$outfile" "$line" 10
    done
}

# -----------------------------------------------------------------------------
# sqlite_read_decisions <db_path> <output_dir>
#   Read decisions table -> decisions.dat
#   Mapping: id, title(=decision), status(=active/superseded),
#            date(=when_context), context(=scope), decision(=choice),
#            consequences(=rationale)
# -----------------------------------------------------------------------------
sqlite_read_decisions() {
    local db_path="$1"
    local output_dir="$2"
    local outfile="${output_dir}/decisions.dat"

    write_header "$outfile" "$DECISIONS_FIELDS"

    local sql="SELECT
        COALESCE(id, ''),
        $(_nl_safe_col "decision"),
        CASE WHEN superseded_by IS NOT NULL AND superseded_by != '' THEN 'superseded' ELSE 'active' END,
        COALESCE(when_context, ''),
        $(_nl_safe_col "scope"),
        $(_nl_safe_col "choice"),
        $(_nl_safe_col "rationale"),
        COALESCE(revisable, ''),
        COALESCE(made_by, ''),
        COALESCE(superseded_by, '')
    FROM decisions
    ORDER BY seq;"

    _sqlite_query "$db_path" "$sql" | while IFS= read -r line; do
        [ -z "$line" ] && continue
        _split_and_append "$outfile" "$line" 10
    done
}

# -----------------------------------------------------------------------------
# sqlite_read_requirements <db_path> <output_dir>
#   Read requirements table -> requirements.dat
#   Mapping: id, type(=class), priority(=status), title(=first 80 chars of
#            description), description, acceptance_criteria(=validation),
#            source
# -----------------------------------------------------------------------------
sqlite_read_requirements() {
    local db_path="$1"
    local output_dir="$2"
    local outfile="${output_dir}/requirements.dat"

    write_header "$outfile" "$REQUIREMENTS_FIELDS"

    local sql="SELECT
        COALESCE(id, ''),
        COALESCE(class, ''),
        COALESCE(status, ''),
        $(_nl_safe_col "SUBSTR(description, 1, 80)"),
        $(_nl_safe_col "description"),
        $(_nl_safe_col "validation"),
        COALESCE(source, ''),
        COALESCE(validation, ''),
        COALESCE(CASE WHEN supporting_slices != '' THEN supporting_slices ELSE primary_owner END, ''),
        COALESCE(superseded_by, '')
    FROM requirements
    ORDER BY id;"

    _sqlite_query "$db_path" "$sql" | while IFS= read -r line; do
        [ -z "$line" ] && continue
        _split_and_append "$outfile" "$line" 10
    done
}

# -----------------------------------------------------------------------------
# sqlite_read_milestones <db_path> <output_dir>
#   Read milestones table -> milestones.dat
#   Mapping: id, title, status, description(=vision),
#            start_date(=created_at), end_date(=completed_at)
# -----------------------------------------------------------------------------
sqlite_read_milestones() {
    local db_path="$1"
    local output_dir="$2"
    local outfile="${output_dir}/milestones.dat"

    write_header "$outfile" "$MILESTONES_FIELDS"

    local sql="SELECT
        COALESCE(id, ''),
        $(_nl_safe_col "title"),
        COALESCE(status, ''),
        $(_nl_safe_col "vision"),
        COALESCE(created_at, ''),
        COALESCE(completed_at, '')
    FROM milestones
    ORDER BY id;"

    _sqlite_query "$db_path" "$sql" | while IFS= read -r line; do
        [ -z "$line" ] && continue
        _split_and_append "$outfile" "$line" 6
    done
}

# -----------------------------------------------------------------------------
# sqlite_read_slices <db_path> <output_dir>
#   Read slices table -> slices.dat
#   Mapping: id, milestone_id, title, status, description(=goal),
#            order(=sequence)
# -----------------------------------------------------------------------------
sqlite_read_slices() {
    local db_path="$1"
    local output_dir="$2"
    local outfile="${output_dir}/slices.dat"

    write_header "$outfile" "$SLICES_FIELDS"

    local sql="SELECT
        COALESCE(id, ''),
        COALESCE(milestone_id, ''),
        $(_nl_safe_col "title"),
        COALESCE(status, ''),
        $(_nl_safe_col "goal"),
        COALESCE(CAST(sequence AS TEXT), '0')
    FROM slices
    ORDER BY milestone_id, id;"

    _sqlite_query "$db_path" "$sql" | while IFS= read -r line; do
        [ -z "$line" ] && continue
        _split_and_append "$outfile" "$line" 6
    done
}

# -----------------------------------------------------------------------------
# sqlite_read_tasks <db_path> <output_dir>
#   Read tasks table -> tasks.dat
#   Mapping: id, slice_id, milestone_id, title, status, description,
#            assignee(=''), depends_on(='')
# -----------------------------------------------------------------------------
sqlite_read_tasks() {
    local db_path="$1"
    local output_dir="$2"
    local outfile="${output_dir}/tasks.dat"

    write_header "$outfile" "$TASKS_FIELDS"

    local sql="SELECT
        COALESCE(id, ''),
        COALESCE(slice_id, ''),
        COALESCE(milestone_id, ''),
        $(_nl_safe_col "title"),
        COALESCE(status, ''),
        $(_nl_safe_col "description"),
        '',
        ''
    FROM tasks
    ORDER BY milestone_id, slice_id, id;"

    _sqlite_query "$db_path" "$sql" | while IFS= read -r line; do
        [ -z "$line" ] && continue
        _split_and_append "$outfile" "$line" 8
    done
}

# -----------------------------------------------------------------------------
# sqlite_read_telemetry <db_path> <output_dir>
#   Read verification_evidence table -> telemetry.dat
#   Mapping: id, timestamp(=created_at), event_type(=verdict),
#            entity_id(=task_id), entity_type(='verification'),
#            details(=command|exit_code|duration_ms), source_file(=''),
#            milestone_id, slice_id
# -----------------------------------------------------------------------------
sqlite_read_telemetry() {
    local db_path="$1"
    local output_dir="$2"
    local outfile="${output_dir}/telemetry.dat"

    write_header "$outfile" "$TELEMETRY_FIELDS"

    local sql="SELECT
        COALESCE(CAST(id AS TEXT), ''),
        COALESCE(created_at, ''),
        COALESCE(verdict, ''),
        COALESCE(task_id, ''),
        'verification',
        $(_nl_safe_col "command") || '|exit=' || COALESCE(CAST(exit_code AS TEXT), '0') || '|dur=' || COALESCE(CAST(duration_ms AS TEXT), '0') || 'ms',
        '',
        COALESCE(milestone_id, ''),
        COALESCE(slice_id, '')
    FROM verification_evidence
    ORDER BY id;"

    _sqlite_query "$db_path" "$sql" | while IFS= read -r line; do
        [ -z "$line" ] && continue
        _split_and_append "$outfile" "$line" 9
    done
}
