#!/usr/bin/env bash
# =============================================================================
# build-fixture.sh — Build minimal spec-kit-shaped fixture tree
# =============================================================================
#
# Generates a spec-kit-shaped project tree at the caller-supplied target
# directory. Used by T02 of M015/P04 to validate the spec-kit migration
# adapter (scripts/migrate/adapters/speckit.sh).
#
# Usage: build-fixture.sh <target-dir>
#
# Compatibility: Bash 3.2+ / POSIX sh; no associative arrays.
# =============================================================================
set -eu

if [ "$#" -ne 1 ]; then
  echo "usage: build-fixture.sh <target-dir>" >&2
  exit 1
fi

TARGET="$1"
test -d "$TARGET" || { echo "FAIL: target dir missing: $TARGET" >&2; exit 1; }

mkdir -p "$TARGET/.specify/memory"
mkdir -p "$TARGET/specs/001-example"

cat > "$TARGET/.specify/memory/constitution.md" <<'EOF'
# Fixture Constitution

Minimal spec-kit-shaped constitution used by the M015 P04 migration
fixture. Any field changes in this file require a corresponding
change to the migration adapter's constitution-move logic.

## Principles

1. Context Minimization
2. Evidence Before Claims
3. Design Before Code
4. Plans Assume Zero Context
5. Fresh Context Per Unit
6. State On Disk Is Truth
7. Knowledge Compounds
EOF

cat > "$TARGET/specs/001-example/spec.md" <<'EOF'
---
feature_branch: 001-example
status: draft
---

# Example Feature

Minimal fixture spec used to exercise the spec-kit migration adapter.
EOF

cat > "$TARGET/README.md" <<'EOF'
# Fixture Project

This is a minimal spec-kit-shaped project generated by
tests/fixtures/m015-p04-speckit-migration/build-fixture.sh.
Not intended for direct use — see the fixture README.
EOF

echo "FIXTURE_BUILT target=$TARGET"
